/**
 * @program: exchange
 * @description: toDo
 * @author: DengWei
 * @create: 2019-05-19
 **/
package com.blockchain.platform.pojo.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

import com.blockchain.platform.constant.BizConst;

/**
 * @program: AssetsFlowDTO
 * @description: 资产传输对象
 * @author: 
 **/
@Builder
@NoArgsConstructor
@AllArgsConstructor
public @Data class AssetsFlowDTO {


    private String id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.USERID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.SYMBOL
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.ADDRESSFROM
     *
     * @mbg.generated
     */
    private String addressFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.ADDRESSTO
     *
     * @mbg.generated
     */
    private String addressTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.OUTFEE
     *
     * @mbg.generated
     */
    private BigDecimal outFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.FEESYMBOL
     *
     * @mbg.generated
     */
    private String feeSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.INDATE
     *
     * @mbg.generated
     */
    private String inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.ORIGINATOR
     *
     * @mbg.generated
     */
    private Integer originator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.C2CAMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal c2cAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.VCODE
     *
     * @mbg.generated
     */
    private Integer vCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.PAYMENTID
     *
     * @mbg.generated
     */
    private Integer paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ASSETS_FLOW.FROZENAMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal frozenAmount;

    private BigDecimal price;
    /**
     * 获取退回状态
     * @return
     */
    public static final String getBackStatus(String prefix) {
        return prefix + BizConst.AssetsConst.STATE_BACK;
    }


}
